name: Build
on:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022
    steps:
      - name: 🧰 Checkout
        uses: actions/checkout@v3

      - name: Run build script
        run: |
          ./build_installer.bat

      - name: Rename installer files
        run: |
          mkdir Upload
          mv Releases/Setup.exe Upload/MyProject-Installer.exe
          mv Releases/Setup.msi Upload/MyProject-Installer.msi
      
      - name: Upload installer files
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: Installers
          path: |
            Upload/*
