name: Build
on:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{matrix.framework}}
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        framework: ["WPF", "Avalonia"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run build script
        run: |
          cd ${{matrix.framework}}
          ./build_installer.bat

      - name: Rename installer files
        run: |
          mkdir Upload
          mv ${{matrix.framework}}/Releases/Setup.exe Upload/MyProject-Installer.exe
          mv ${{matrix.framework}}/Releases/Setup.msi Upload/MyProject-Installer.msi
      
      - name: Upload installer files
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: ${{matrix.framework}} Installers
          path: |
            Upload/*
